### ISSUE TITLE
Last 12 months reading

### ISSUE THREAD

**Issue by Hajsiu** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#5]
Hi Piotr,

Is there a way to show readings for last 12 months instead of specific year from January to December? Tauron calculates the power "left to take" from generation and consuption basing on last 12 months (it changed few months ago) so that would be great to have a possibility to check how much power we can currently use to have a 0'ish bill.
I would really appreciate if you could make some additional lines of code!

**Comment by Hajsiu** [comment]
Hi Piotr, are you gonna work on this feature soon? Thats actually the main feature i would need and i think many peoples other peoples too. I would really appreciate if you could make it work!

**Comment by PiotrMachowski** [comment]
What kind of range should it be?
 - 10.01.2020 - 10.01.2021
 - 01.01.2020 - 10.01.2021
 - maybe another one?

**Comment by Hajsiu** [comment]
As i know the settlement period is 365 days so the range like 10.01.2020-10.01.2021 should be the correct one.

> System rozliczeń dla Prosumentów umożliwia odbiór wyprodukowanych nadwyżek energii przesłanych do sieci w okresie do 365 dni od daty odczytu rozliczeniowego.

**Comment by tomhash2** [comment]
But there is one big problem. When you try to get data for period there is no way to take into account generated power, only consumption. Try it for yourself on eLicznik website.

**Comment by Hajsiu** [comment]
> But there is one big problem. When you try to get data for period there is no way to take into account generated power, only consumption. Try it for yourself on eLicznik website.

Could you make that option for consumption only so? I would take the generation data from inverter directly.

**Comment by Hajsiu** [comment]
Hi Piotr,

I know its pretty old issue but any update on this?

**Comment by PiotrMachowski** [comment]
Hi @Hajsiu,

Recently I've been working almost exclusively on Vacuum Map card

**Comment by aaddiikk** [comment]
> But there is one big problem. When you try to get data for period there is no way to take into account generated power, only consumption. Try it for yourself on eLicznik website.

Aktualny, there is a way to achieve both consumption and production parameters. You need to read values for each month individually. Doing so, and then summing up the values, would do the trick. 

Optimal solution would be to have two config options - one for definition of “billing start” (that would be a date of start of your billing cycle) and “billing frequency” (for definition of billing period like monthly - for normal customers, half-yearly and yearly - for prosumers). 

Another good addition would be config option to include in calculations extra fee for TAURON. This would be 20% or 30% depending on power of solar installation. This way we would have precise energy budget meter and bill prediction.

**Comment by PiotrMachowski** [comment]
Hi @Hajsiu,

Is this still a valid feature request?

**Comment by Hajsiu** [comment]
Hi @PiotrMachowski,

Yes, it still is as i calculate the "energy left to use" manually.

**Comment by PiotrMachowski** [comment]
Added in `v2.3.2`

**Comment by aaddiikk** [comment]
Do I understand correctly, that this feature does not take into consideration the date, when the billing period starts/ends? In my case for instance (as a prosumer), my billing period starts at 1st of April and ends on last day of March next year. So in order to calculate the “remaining energy” or bill amount I cannot simply rely on last 12 months as it is shown in the example.On 19 Jan 2023, at 02:01, Piotr Machowski ***@***.***> wrote:﻿
Added in v2.3.2

**Comment by PiotrMachowski** [comment]
@aaddiikk yes, it is `19.01.2022-19.01.2023` kind of range.

**Comment by aaddiikk** [comment]
@PiotrMachowski 
Ok then, so as it is right now gives no value for prosument calculations.

As mentioned previously, we would need to have two new variables to define start date of billing period (eg. 1st of April in my case) and period duration (most of prosumers use 1Y, although I know there are some with 6M). This way we will get precise “energy budget left” instead of what ‘last 12 months’ returns.

Want me to reopen this issue or submit new one?

**Comment by PiotrMachowski** [comment]
@Hajsiu in comments above described it the following way. Has this approach changed?

> As i know the settlement period is 365 days so the range like 10.01.2020-10.01.2021 should be the correct one.
> 
> > System rozliczeń dla Prosumentów umożliwia odbiór wyprodukowanych nadwyżek energii przesłanych do sieci w okresie do 365 dni od daty odczytu rozliczeniowego.

**Comment by aaddiikk** [comment]
@PiotrMachowski 
And it is like that BUT the issue is that the starting point depends on when the contract is signed between the prosumer and Tauron. 

Just to give you an example. My solar panels and related stuff were installed somewhere in the beginning of March. Next, Tauron provided updated contract, with start date of 1.04. The contract is about 1Y cycles. So, after full 12 months, they are calculating both production and consumption, applying the 0.8 factor fee on top of it and submit an invoice to the customer.

**Comment by PiotrMachowski** [comment]
@aaddiikk ok, sooooo everybody has a different starting point and this point is no later than 365 days ago, right?

**Comment by mmarcines** [comment]
@PiotrMachowski  right. In my case while signing contract tauron suggested me to have 6 months long billing period but I've changed that to 12 months and that time I was able to indicate starting point (in my case billing year = callendar year means being Jan and end of Dec).

**Comment by PiotrMachowski** [comment]
Ok, this makes things a little bit more complicated...

**Comment by aaddiikk** [comment]
> @aaddiikk ok, sooooo everybody has a different starting point and this point is no later than 365 days ago, right?

Yes, indeed. So the logic here is that on firs date of billing (starting date of 6 or 12 months period) the energy budget is “0”. During the year you will have months where you will produce more (summer) than consume or the other way around (winter). After this 6M or 12M ends, Tauron will calculate this ratio and issue the bill.

**Comment by PiotrMachowski** [comment]
New release (`v2.4.0`) makes it possible to create sensors with a configurable start time
